package com.theshire.app.ui

import android.content.Context
import com.theshire.app.data.AppDatabase
import com.theshire.app.data.LegumeEntity
import kotlinx.coroutines.flow.Flow

class LegumeRepository(context: Context) {
    
    private val legumeDao = AppDatabase.getDatabase(context).legumeDao()
    
    val legumes: Flow<List<LegumeEntity>> = legumeDao.getAllLegumes()
    
    suspend fun ajouterLegumesPredefinis() {
        if (legumeDao.countLegumes() == 0) {
            getLegumesPredefinis().forEach { legume ->
                legumeDao.insertLegume(legume)
            }
        }
    }
    
    suspend fun supprimerLegume(legume: LegumeEntity) {
        legumeDao.deleteLegume(legume)
    }
    
    private fun getLegumesPredefinis(): List<LegumeEntity> {
        return listOf(
            // ===== LÉGUMES RACINES =====
            LegumeEntity(
                nom = "Carotte",
                categorie = "Racine",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Meuble, sableux, sans cailloux",
                arrosage = "Régulier mais modéré, éviter l'excès d'eau",
                temperature = "Rustique, supporte le froid",
                semis = "Mars à juillet",
                plantation = "Semis direct en pleine terre",
                recolte = "3 à 4 mois après semis",
                entretien = "Éclaircir les plants à 5 cm. Biner régulièrement.",
                maladies = "Mouche de la carotte, mildiou",
                prevention = "Associer avec oignons, poireaux. Voile anti-insectes.",
                bonnesAssociations = "Oignon, poireau, tomate, salade",
                mauvaisesAssociations = "Aneth, persil"
            ),
            LegumeEntity(
                nom = "Pomme de terre",
                categorie = "Tubercule",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Meuble, profond",
                arrosage = "Régulier sans excès",
                temperature = "Rustique",
                semis = "Mars à avril (plantation)",
                plantation = "Mars à avril",
                recolte = "90 à 120 jours après plantation",
                entretien = "Butter régulièrement, pailler",
                maladies = "Mildiou, doryphore",
                prevention = "Purin de prêle, ramassage manuel des doryphores",
                bonnesAssociations = "Haricot, maïs, chou",
                mauvaisesAssociations = "Tomate, aubergine"
            ),
            LegumeEntity(
                nom = "Radis",
                categorie = "Racine",
                difficulte = "Très facile",
                exposition = "Soleil à mi-ombre",
                sol = "Léger, frais",
                arrosage = "Régulier pour éviter le piquant",
                temperature = "Rustique",
                semis = "Mars à septembre",
                plantation = "Semis direct",
                recolte = "3 à 4 semaines après semis",
                entretien = "Arrosage quotidien, éclaircir",
                maladies = "Altises, pourriture",
                prevention = "Voile anti-insectes, cendre",
                bonnesAssociations = "Carotte, salade, tomate",
                mauvaisesAssociations = "Chou"
            ),
            LegumeEntity(
                nom = "Betterave",
                categorie = "Racine",
                difficulte = "Facile",
                exposition = "Soleil à mi-ombre",
                sol = "Meuble, profond",
                arrosage = "Régulier",
                temperature = "Rustique",
                semis = "Avril à juin",
                plantation = "Semis direct",
                recolte = "3 à 4 mois après semis",
                entretien = "Éclaircir, biner",
                maladies = "Cercosporiose",
                prevention = "Rotation des cultures, purin de prêle",
                bonnesAssociations = "Oignon, chou, salade",
                mauvaisesAssociations = "Épinard"
            ),
            LegumeEntity(
                nom = "Navet",
                categorie = "Racine",
                difficulte = "Facile",
                exposition = "Soleil à mi-ombre",
                sol = "Meuble, frais",
                arrosage = "Régulier",
                temperature = "Rustique",
                semis = "Mars à août",
                plantation = "Semis direct",
                recolte = "2 à 3 mois après semis",
                entretien = "Éclaircir, biner",
                maladies = "Altises, mildiou",
                prevention = "Voile anti-insectes, cendre",
                bonnesAssociations = "Pois, salade, haricot",
                mauvaisesAssociations = "Chou"
            ),
            LegumeEntity(
                nom = "Panais",
                categorie = "Racine ancienne",
                difficulte = "Facile",
                exposition = "Soleil à mi-ombre",
                sol = "Profond, meuble, frais",
                arrosage = "Régulier, surtout en été",
                temperature = "Très rustique",
                semis = "Mars à juin",
                plantation = "Semis direct",
                recolte = "4 à 5 mois après semis",
                entretien = "Pailler, biner régulièrement",
                maladies = "Mouche de la carotte",
                prevention = "Voile anti-insectes, purin de prêle",
                bonnesAssociations = "Oignon, poireau, radis",
                mauvaisesAssociations = "Aneth"
            ),
            LegumeEntity(
                nom = "Rutabaga",
                categorie = "Racine ancienne",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Frais, profond, riche",
                arrosage = "Abondant et régulier",
                temperature = "Très rustique",
                semis = "Avril à juin",
                plantation = "Semis direct ou repiquage",
                recolte = "3 à 4 mois après semis",
                entretien = "Pailler, arroser régulièrement",
                maladies = "Hernie du chou",
                prevention = "Rotation des cultures, chaulage",
                bonnesAssociations = "Oignon, haricot, pois",
                mauvaisesAssociations = "Autre chou"
            ),
            LegumeEntity(
                nom = "Topinambour",
                categorie = "Tubercule ancien",
                difficulte = "Très facile",
                exposition = "Plein soleil",
                sol = "Tout sol, même pauvre",
                arrosage = "Faible, résiste à la sécheresse",
                temperature = "Très rustique",
                semis = "Mars à avril (plantation)",
                plantation = "Mars à avril",
                recolte = "Octobre à mars",
                entretien = "Butter, limiter l'expansion",
                maladies = "Oïdium",
                prevention = "Purin de prêle, aération",
                bonnesAssociations = "Maïs, haricot",
                mauvaisesAssociations = "Pomme de terre"
            ),
            LegumeEntity(
                nom = "Cerfeuil tubéreux",
                categorie = "Racine ancienne",
                difficulte = "Moyen",
                exposition = "Mi-ombre",
                sol = "Frais, riche, bien drainé",
                arrosage = "Régulier",
                temperature = "Rustique",
                semis = "Octobre à novembre",
                plantation = "Semis direct",
                recolte = "Juillet à septembre",
                entretien = "Pailler, désherber",
                maladies = "Fonte des semis",
                prevention = "Bonne aération, purin de prêle",
                bonnesAssociations = "Salade, épinard",
                mauvaisesAssociations = "Carotte"
            ),

            // ===== LÉGUMES FRUITS =====
            LegumeEntity(
                nom = "Tomate",
                categorie = "Fruit",
                difficulte = "Moyen",
                exposition = "Plein soleil",
                sol = "Riche en humus, bien drainé",
                arrosage = "Au pied, régulier sans mouiller les feuilles",
                temperature = "Frileuse, craint le gel",
                semis = "Février à avril (sous abri)",
                plantation = "Mai (après les gelées)",
                recolte = "Juillet à octobre",
                entretien = "Tuteurer, effeuiller, supprimer les gourmands",
                maladies = "Mildiou, cul noir",
                prevention = "Purin d'ortie, éviter l'humidité sur feuillage",
                bonnesAssociations = "Basilic, carotte, oignon, persil",
                mauvaisesAssociations = "Pomme de terre, concombre"
            ),
            LegumeEntity(
                nom = "Courgette",
                categorie = "Fruit",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Riche en compost",
                arrosage = "Abondant au pied",
                temperature = "Frileuse, craint le gel",
                semis = "Avril (sous abri)",
                plantation = "Mai",
                recolte = "Juin à octobre",
                entretien = "Pailler, supprimer les fruits trop gros",
                maladies = "Oïdium, pourriture",
                prevention = "Purin de prêle, éviter de mouiller les feuilles",
                bonnesAssociations = "Haricot, salade, menthe",
                mauvaisesAssociations = "Pomme de terre"
            ),
            LegumeEntity(
                nom = "Poivron",
                categorie = "Fruit",
                difficulte = "Moyen",
                exposition = "Plein soleil",
                sol = "Riche, bien drainé",
                arrosage = "Régulier au pied",
                temperature = "Très frileux",
                semis = "Février à mars (sous abri)",
                plantation = "Mai",
                recolte = "Juillet à octobre",
                entretien = "Tuteurer, pailler",
                maladies = "Pucerons, mildiou",
                prevention = "Savon noir, purin d'ortie",
                bonnesAssociations = "Basilic, carotte, tomate",
                mauvaisesAssociations = "Fenouil"
            ),
            LegumeEntity(
                nom = "Aubergine",
                categorie = "Fruit",
                difficulte = "Difficile",
                exposition = "Plein soleil",
                sol = "Riche, profond",
                arrosage = "Abondant au pied",
                temperature = "Très frileuse",
                semis = "Février à mars (sous abri)",
                plantation = "Mai",
                recolte = "Juillet à octobre",
                entretien = "Tuteurer, pailler",
                maladies = "Doryphore, mildiou",
                prevention = "Ramassage manuel, purin d'ortie",
                bonnesAssociations = "Haricot, basilic, thym",
                mauvaisesAssociations = "Pomme de terre"
            ),
            LegumeEntity(
                nom = "Concombre",
                categorie = "Fruit",
                difficulte = "Moyen",
                exposition = "Plein soleil",
                sol = "Riche, bien drainé",
                arrosage = "Très abondant",
                temperature = "Frileux",
                semis = "Mars à avril (sous abri)",
                plantation = "Mai",
                recolte = "Juillet à septembre",
                entretien = "Tuteurer, pailler",
                maladies = "Oïdium, mildiou",
                prevention = "Purin de prêle, éviter de mouiller les feuilles",
                bonnesAssociations = "Maïs, haricot, salade",
                mauvaisesAssociations = "Tomate, pomme de terre"
            ),
            LegumeEntity(
                nom = "Potiron",
                categorie = "Cucurbitacée",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Très riche en compost",
                arrosage = "Très abondant",
                temperature = "Frileux",
                semis = "Avril (sous abri)",
                plantation = "Mai",
                recolte = "Septembre à novembre",
                entretien = "Pailler, limiter les fruits par plant",
                maladies = "Oïdium, pourriture",
                prevention = "Purin de prêle, éviter de mouiller les feuilles",
                bonnesAssociations = "Maïs, haricot",
                mauvaisesAssociations = "Pomme de terre"
            ),

            // ===== LÉGUMES FEUILLES =====
            LegumeEntity(
                nom = "Salade",
                categorie = "Feuille",
                difficulte = "Facile",
                exposition = "Mi-ombre à soleil",
                sol = "Frais, riche en humus",
                arrosage = "Régulier, garder le sol frais",
                temperature = "Rustique, préfère la fraîcheur",
                semis = "Mars à septembre",
                plantation = "Repiquage ou semis direct",
                recolte = "4 à 8 semaines après semis",
                entretien = "Pailler pour garder l'humidité, éclaircir",
                maladies = "Limaces, botrytis",
                prevention = "Cendre autour des plants, purin de prêle",
                bonnesAssociations = "Carotte, radis, fraisier, concombre",
                mauvaisesAssociations = "Céleri, persil"
            ),
            LegumeEntity(
                nom = "Épinard",
                categorie = "Feuille",
                difficulte = "Facile",
                exposition = "Mi-ombre",
                sol = "Frais, riche en humus",
                arrosage = "Régulier, sol toujours frais",
                temperature = "Rustique",
                semis = "Mars à mai, août à septembre",
                plantation = "Semis direct",
                recolte = "6 à 8 semaines après semis",
                entretien = "Éclaircir, pailler",
                maladies = "Mildiou, pucerons",
                prevention = "Purin d'ortie, savon noir",
                bonnesAssociations = "Fraisier, pois, chou",
                mauvaisesAssociations = "Betterave"
            ),
            LegumeEntity(
                nom = "Chou frisé (Kale)",
                categorie = "Feuille",
                difficulte = "Facile",
                exposition = "Soleil à mi-ombre",
                sol = "Riche, profond",
                arrosage = "Régulier",
                temperature = "Très rustique",
                semis = "Mars à juin",
                plantation = "Avril à juillet",
                recolte = "Septembre à mars",
                entretien = "Pailler, arroser",
                maladies = "Piéride du chou",
                prevention = "Voile anti-insectes",
                bonnesAssociations = "Oignon, pomme de terre, haricot",
                mauvaisesAssociations = "Fraise, tomate"
            ),
            LegumeEntity(
                nom = "Cardon",
                categorie = "Feuille ancienne",
                difficulte = "Moyen",
                exposition = "Plein soleil",
                sol = "Profond, riche, frais",
                arrosage = "Abondant en été",
                temperature = "Rustique",
                semis = "Avril à mai",
                plantation = "Mai à juin",
                recolte = "Octobre à décembre",
                entretien = "Butter, blanchir les côtes",
                maladies = "Pucerons",
                prevention = "Savon noir, purin d'ortie",
                bonnesAssociations = "Chou, haricot",
                mauvaisesAssociations = "Pomme de terre"
            ),

            // ===== LÉGUMINEUSES =====
            LegumeEntity(
                nom = "Haricot vert",
                categorie = "Légumineuse",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Léger, bien drainé",
                arrosage = "Régulier, surtout à la floraison",
                temperature = "Craint le gel",
                semis = "Avril à juillet",
                plantation = "Semis direct",
                recolte = "2 à 3 mois après semis",
                entretien = "Butter les plants, pailler",
                maladies = "Anthracnose, rouille",
                prevention = "Rotation des cultures, purin de prêle",
                bonnesAssociations = "Maïs, courge, carotte",
                mauvaisesAssociations = "Ail, oignon, fenouil"
            ),
            LegumeEntity(
                nom = "Petit pois",
                categorie = "Légumineuse",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Léger, bien drainé",
                arrosage = "Régulier à la floraison",
                temperature = "Rustique",
                semis = "Février à mai",
                plantation = "Semis direct",
                recolte = "3 mois après semis",
                entretien = "Tuteurer, pailler",
                maladies = "Oïdium, anthracnose",
                prevention = "Purin de prêle, rotation des cultures",
                bonnesAssociations = "Carotte, radis, salade",
                mauvaisesAssociations = "Ail, oignon"
            ),

            // ===== ALLIACÉS =====
            LegumeEntity(
                nom = "Oignon",
                categorie = "Alliacé",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Léger, bien drainé",
                arrosage = "Modéré, stopper avant récolte",
                temperature = "Rustique",
                semis = "Février à avril",
                plantation = "Mars à avril",
                recolte = "Juillet à septembre",
                entretien = "Biner, éviter l'humidité stagnante",
                maladies = "Mildiou, pourriture",
                prevention = "Rotation des cultures, purin de prêle",
                bonnesAssociations = "Carotte, betterave, salade",
                mauvaisesAssociations = "Haricot, pois"
            ),
            LegumeEntity(
                nom = "Poireau",
                categorie = "Alliacé",
                difficulte = "Moyen",
                exposition = "Soleil à mi-ombre",
                sol = "Riche, profond, frais",
                arrosage = "Régulier, surtout en été",
                temperature = "Très rustique",
                semis = "Février à avril",
                plantation = "Mai à juillet",
                recolte = "Octobre à mars",
                entretien = "Butter pour blanchir, pailler",
                maladies = "Rouille, teigne",
                prevention = "Purin de prêle, rotation des cultures",
                bonnesAssociations = "Carotte, céleri, fraisier",
                mauvaisesAssociations = "Haricot, pois"
            ),
            LegumeEntity(
                nom = "Ail",
                categorie = "Alliacé",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Léger, bien drainé",
                arrosage = "Modéré",
                temperature = "Rustique",
                semis = "Octobre à novembre ou février à mars",
                plantation = "Octobre à novembre",
                recolte = "Juin à juillet",
                entretien = "Biner, éviter l'excès d'eau",
                maladies = "Rouille, pourriture",
                prevention = "Rotation des cultures, purin de prêle",
                bonnesAssociations = "Carotte, betterave, fraisier",
                mauvaisesAssociations = "Haricot, pois"
            ),

            // ===== CHOUX =====
            LegumeEntity(
                nom = "Brocoli",
                categorie = "Chou",
                difficulte = "Moyen",
                exposition = "Plein soleil",
                sol = "Riche, profond, frais",
                arrosage = "Abondant et régulier",
                temperature = "Rustique",
                semis = "Mars à juin",
                plantation = "Avril à juillet",
                recolte = "3 à 4 mois après plantation",
                entretien = "Pailler, arroser régulièrement",
                maladies = "Piéride du chou, hernie",
                prevention = "Voile anti-insectes, rotation des cultures",
                bonnesAssociations = "Pomme de terre, oignon, aneth",
                mauvaisesAssociations = "Fraise, tomate"
            ),
            LegumeEntity(
                nom = "Chou-fleur",
                categorie = "Chou",
                difficulte = "Moyen",
                exposition = "Plein soleil",
                sol = "Riche, profond, frais",
                arrosage = "Abondant et régulier",
                temperature = "Rustique",
                semis = "Mars à juin",
                plantation = "Avril à juillet",
                recolte = "3 à 4 mois après plantation",
                entretien = "Pailler, arroser régulièrement",
                maladies = "Piéride du chou, hernie",
                prevention = "Voile anti-insectes, rotation des cultures",
                bonnesAssociations = "Haricot, céleri, thym",
                mauvaisesAssociations = "Fraise, tomate"
            ),

            // ===== HERBES AROMATIQUES =====
            LegumeEntity(
                nom = "Basilic",
                categorie = "Aromatique",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Riche, frais, bien drainé",
                arrosage = "Régulier, au pied",
                temperature = "Très frileux",
                semis = "Mars à mai (sous abri)",
                plantation = "Mai",
                recolte = "Juin à octobre",
                entretien = "Pincer les fleurs, récolter régulièrement",
                maladies = "Fonte des semis, mildiou",
                prevention = "Éviter l'excès d'eau, bonne aération",
                bonnesAssociations = "Tomate, poivron, courgette",
                mauvaisesAssociations = "Rue"
            ),
            LegumeEntity(
                nom = "Persil",
                categorie = "Aromatique",
                difficulte = "Facile",
                exposition = "Mi-ombre à soleil",
                sol = "Frais, riche, bien drainé",
                arrosage = "Régulier",
                temperature = "Rustique",
                semis = "Mars à août",
                plantation = "Semis direct",
                recolte = "Toute l'année",
                entretien = "Couper les feuilles régulièrement",
                maladies = "Mildiou, pucerons",
                prevention = "Purin d'ortie, savon noir",
                bonnesAssociations = "Tomate, carotte, oignon",
                mauvaisesAssociations = "Salade"
            ),
            LegumeEntity(
                nom = "Menthe",
                categorie = "Aromatique",
                difficulte = "Très facile",
                exposition = "Mi-ombre",
                sol = "Frais, riche",
                arrosage = "Abondant",
                temperature = "Très rustique",
                semis = "Mars à mai (plantation)",
                plantation = "Mars à mai",
                recolte = "Avril à octobre",
                entretien = "Limiter l'expansion, tailler",
                maladies = "Rouille",
                prevention = "Purin de prêle, aération",
                bonnesAssociations = "Chou, tomate, courgette",
                mauvaisesAssociations = "Aucune"
            ),
            LegumeEntity(
                nom = "Thym",
                categorie = "Aromatique",
                difficulte = "Très facile",
                exposition = "Plein soleil",
                sol = "Sec, pauvre, bien drainé",
                arrosage = "Faible, résiste à la sécheresse",
                temperature = "Rustique",
                semis = "Mars à mai",
                plantation = "Mars à mai",
                recolte = "Toute l'année",
                entretien = "Tailler après floraison",
                maladies = "Aucune majeure",
                prevention = "Bonne aération",
                bonnesAssociations = "Chou, fraisier, aubergine",
                mauvaisesAssociations = "Aucune"
            ),
            LegumeEntity(
                nom = "Romarin",
                categorie = "Aromatique",
                difficulte = "Très facile",
                exposition = "Plein soleil",
                sol = "Sec, calcaire, bien drainé",
                arrosage = "Faible",
                temperature = "Rustique",
                semis = "Mars à mai (plantation)",
                plantation = "Mars à mai",
                recolte = "Toute l'année",
                entretien = "Tailler après floraison",
                maladies = "Aucune majeure",
                prevention = "Bonne aération",
                bonnesAssociations = "Haricot, chou, carotte",
                mauvaisesAssociations = "Aucune"
            ),
            LegumeEntity(
                nom = "Ciboulette",
                categorie = "Aromatique",
                difficulte = "Très facile",
                exposition = "Soleil à mi-ombre",
                sol = "Frais, riche",
                arrosage = "Régulier",
                temperature = "Rustique",
                semis = "Mars à mai",
                plantation = "Mars à mai",
                recolte = "Avril à octobre",
                entretien = "Couper régulièrement",
                maladies = "Rouille",
                prevention = "Purin de prêle",
                bonnesAssociations = "Carotte, tomate, pomme de terre",
                mauvaisesAssociations = "Haricot, pois"
            ),
            LegumeEntity(
                nom = "Coriandre",
                categorie = "Aromatique",
                difficulte = "Facile",
                exposition = "Soleil à mi-ombre",
                sol = "Léger, frais, bien drainé",
                arrosage = "Régulier",
                temperature = "Rustique",
                semis = "Mars à septembre",
                plantation = "Semis direct",
                recolte = "6 à 8 semaines après semis",
                entretien = "Éclaircir, récolter les feuilles",
                maladies = "Fonte des semis",
                prevention = "Bonne aération",
                bonnesAssociations = "Carotte, chou, concombre",
                mauvaisesAssociations = "Fenouil"
            ),
            LegumeEntity(
                nom = "Aneth",
                categorie = "Aromatique",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Léger, bien drainé",
                arrosage = "Modéré",
                temperature = "Rustique",
                semis = "Avril à juillet",
                plantation = "Semis direct",
                recolte = "Juin à septembre",
                entretien = "Éclaircir, tuteurer si nécessaire",
                maladies = "Fonte des semis",
                prevention = "Bonne aération",
                bonnesAssociations = "Chou, concombre, oignon",
                mauvaisesAssociations = "Carotte, tomate"
            )
        )
    }
}
