package com.theshire.app.ui

import android.content.Context
import com.theshire.app.data.AppDatabase
import com.theshire.app.data.LegumeEntity
import kotlinx.coroutines.flow.Flow

class LegumeRepository(context: Context) {
    
    private val legumeDao = AppDatabase.getDatabase(context).legumeDao()
    
    val legumes: Flow<List<LegumeEntity>> = legumeDao.getAllLegumes()
    
    suspend fun ajouterLegumesPredefinis() {
        if (legumeDao.countLegumes() == 0) {
            getLegumesPredefinis().forEach { legume ->
                legumeDao.insertLegume(legume)
            }
        }
    }
    
    suspend fun supprimerLegume(legume: LegumeEntity) {
        legumeDao.deleteLegume(legume)
    }
    
    private fun getLegumesPredefinis(): List<LegumeEntity> {
        return listOf(
            // ===== LÉGUMES RACINES =====
            LegumeEntity(
                nom = "Carotte",
                categorie = "Racine",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Meuble, sableux, sans cailloux",
                arrosage = "Régulier mais modéré, éviter l'excès d'eau",
                temperature = "Rustique, supporte le froid",
                semis = "Mars à juillet",
                plantation = "Semis direct en pleine terre",
                recolte = "3 à 4 mois après semis",
                entretien = "Éclaircir les plants à 5 cm. Biner régulièrement.",
                maladies = "Mouche de la carotte, mildiou",
                prevention = "Associer avec oignons, poireaux. Voile anti-insectes.",
                bonnesAssociations = "Oignon, poireau, tomate, salade",
                mauvaisesAssociations = "Aneth, persil",
                conservation = "Conservation : En cave dans du sable sec (plusieurs mois). Congélation : blanchir 3 min puis congeler. Lactofermentation : râper et saler à 2%. Conserves : en rondelles dans saumure.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Pomme de terre",
                categorie = "Tubercule",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Meuble, profond",
                arrosage = "Régulier sans excès",
                temperature = "Rustique",
                semis = "Mars à avril (plantation)",
                plantation = "Mars à avril",
                recolte = "90 à 120 jours après plantation",
                entretien = "Butter régulièrement, pailler",
                maladies = "Mildiou, doryphore",
                prevention = "Purin de prêle, ramassage manuel des doryphores",
                bonnesAssociations = "Haricot, maïs, chou",
                mauvaisesAssociations = "Tomate, aubergine",
                conservation = "Conservation : En cave sombre et fraîche (4-8°C) dans des cagettes aérées (plusieurs mois). Ne pas congeler crues. Séchage : en purée déshydratée. Conserves : en dés stérilisés.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Radis",
                categorie = "Racine",
                difficulte = "Très facile",
                exposition = "Soleil à mi-ombre",
                sol = "Léger, frais",
                arrosage = "Régulier pour éviter le piquant",
                temperature = "Rustique",
                semis = "Mars à septembre",
                plantation = "Semis direct",
                recolte = "3 à 4 semaines après semis",
                entretien = "Arrosage quotidien, éclaircir",
                maladies = "Altises, pourriture",
                prevention = "Voile anti-insectes, cendre",
                bonnesAssociations = "Carotte, salade, tomate",
                mauvaisesAssociations = "Chou",
                conservation = "Conservation : Au réfrigérateur 1-2 semaines dans un linge humide. Lactofermentation : entiers ou en rondelles salés à 2%. Conserves : au vinaigre (pickles).",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Betterave",
                categorie = "Racine",
                difficulte = "Facile",
                exposition = "Soleil à mi-ombre",
                sol = "Meuble, profond",
                arrosage = "Régulier",
                temperature = "Rustique",
                semis = "Avril à juin",
                plantation = "Semis direct",
                recolte = "3 à 4 mois après semis",
                entretien = "Éclaircir, biner",
                maladies = "Cercosporiose",
                prevention = "Rotation des cultures, purin de prêle",
                bonnesAssociations = "Oignon, chou, salade",
                mauvaisesAssociations = "Épinard",
                conservation = "Conservation : En cave dans du sable (plusieurs mois). Cuites au réfrigérateur 1 semaine. Conserves : cuites et stérilisées entières ou en dés. Lactofermentation : râpées et salées.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Navet",
                categorie = "Racine",
                difficulte = "Facile",
                exposition = "Soleil à mi-ombre",
                sol = "Meuble, frais",
                arrosage = "Régulier",
                temperature = "Rustique",
                semis = "Mars à août",
                plantation = "Semis direct",
                recolte = "2 à 3 mois après semis",
                entretien = "Éclaircir, biner",
                maladies = "Altises, mildiou",
                prevention = "Voile anti-insectes, cendre",
                bonnesAssociations = "Pois, salade, haricot",
                mauvaisesAssociations = "Chou",
                conservation = "Conservation : En cave dans du sable (3-4 mois). Congélation : blanchir 3 min. Lactofermentation : en rondelles salées à 2%. Conserves : au vinaigre.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Panais",
                categorie = "Racine ancienne",
                difficulte = "Facile",
                exposition = "Soleil à mi-ombre",
                sol = "Profond, meuble, frais",
                arrosage = "Régulier, surtout en été",
                temperature = "Très rustique",
                semis = "Mars à juin",
                plantation = "Semis direct",
                recolte = "4 à 5 mois après semis",
                entretien = "Pailler, biner régulièrement",
                maladies = "Mouche de la carotte",
                prevention = "Voile anti-insectes, purin de prêle",
                bonnesAssociations = "Oignon, poireau, radis",
                mauvaisesAssociations = "Aneth",
                conservation = "Conservation : En terre tout l'hiver (résiste au gel). En cave dans du sable. Congélation : blanchir 3 min. Séchage : en chips déshydratées.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Rutabaga",
                categorie = "Racine ancienne",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Frais, profond, riche",
                arrosage = "Abondant et régulier",
                temperature = "Très rustique",
                semis = "Avril à juin",
                plantation = "Semis direct ou repiquage",
                recolte = "3 à 4 mois après semis",
                entretien = "Pailler, arroser régulièrement",
                maladies = "Hernie du chou",
                prevention = "Rotation des cultures, chaulage",
                bonnesAssociations = "Oignon, haricot, pois",
                mauvaisesAssociations = "Autre chou",
                conservation = "Conservation : En cave dans du sable (plusieurs mois). Congélation : blanchir 3 min. Conserves : en dés stérilisés. Lactofermentation : râpé et salé.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Topinambour",
                categorie = "Tubercule ancien",
                difficulte = "Très facile",
                exposition = "Plein soleil",
                sol = "Tout sol, même pauvre",
                arrosage = "Faible, résiste à la sécheresse",
                temperature = "Très rustique",
                semis = "Mars à avril (plantation)",
                plantation = "Mars à avril",
                recolte = "Octobre à mars",
                entretien = "Butter, limiter l'expansion",
                maladies = "Oïdium",
                prevention = "Purin de prêle, aération",
                bonnesAssociations = "Maïs, haricot",
                mauvaisesAssociations = "Pomme de terre",
                conservation = "Conservation : En terre (récolter au fur et à mesure). Au réfrigérateur 1-2 semaines dans un sac perforé. Lactofermentation : en rondelles salées. Conserves : au vinaigre.",
                estVivace = true,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Cerfeuil tubéreux",
                categorie = "Racine ancienne",
                difficulte = "Moyen",
                exposition = "Mi-ombre",
                sol = "Frais, riche, bien drainé",
                arrosage = "Régulier",
                temperature = "Rustique",
                semis = "Octobre à novembre",
                plantation = "Semis direct",
                recolte = "Juillet à septembre",
                entretien = "Pailler, désherber",
                maladies = "Fonte des semis",
                prevention = "Bonne aération, purin de prêle",
                bonnesAssociations = "Salade, épinard",
                mauvaisesAssociations = "Carotte",
                conservation = "Conservation : En cave dans du sable (2-3 mois). Congélation : blanchir 2 min. Séchage : en rondelles déshydratées.",
                estVivace = false,
                estFleur = false
            ),

            // ===== LÉGUMES FRUITS =====
            LegumeEntity(
                nom = "Tomate",
                categorie = "Fruit",
                difficulte = "Moyen",
                exposition = "Plein soleil",
                sol = "Riche en humus, bien drainé",
                arrosage = "Au pied, régulier sans mouiller les feuilles",
                temperature = "Frileuse, craint le gel",
                semis = "Février à avril (sous abri)",
                plantation = "Mai (après les gelées)",
                recolte = "Juillet à octobre",
                entretien = "Tuteurer, effeuiller, supprimer les gourmands",
                maladies = "Mildiou, cul noir",
                prevention = "Purin d'ortie, éviter l'humidité sur feuillage",
                bonnesAssociations = "Basilic, carotte, oignon, persil",
                mauvaisesAssociations = "Pomme de terre, concombre",
                conservation = "Conservation : Conserves : coulis ou tomates pelées stérilisées. Séchage : en tranches au déshydrateur ou au four. Congélation : entières ou en coulis. Lactofermentation : cerises entières salées.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Courgette",
                categorie = "Fruit",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Riche en compost",
                arrosage = "Abondant au pied",
                temperature = "Frileuse, craint le gel",
                semis = "Avril (sous abri)",
                plantation = "Mai",
                recolte = "Juin à octobre",
                entretien = "Pailler, supprimer les fruits trop gros",
                maladies = "Oïdium, pourriture",
                prevention = "Purin de prêle, éviter de mouiller les feuilles",
                bonnesAssociations = "Haricot, salade, menthe",
                mauvaisesAssociations = "Pomme de terre",
                conservation = "Conservation : Congélation : en rondelles blanchies 3 min. Conserves : ratatouille stérilisée. Lactofermentation : en bâtonnets salés. Séchage : en chips déshydratées.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Poivron",
                categorie = "Fruit",
                difficulte = "Moyen",
                exposition = "Plein soleil",
                sol = "Riche, bien drainé",
                arrosage = "Régulier au pied",
                temperature = "Très frileux",
                semis = "Février à mars (sous abri)",
                plantation = "Mai",
                recolte = "Juillet à octobre",
                entretien = "Tuteurer, pailler",
                maladies = "Pucerons, mildiou",
                prevention = "Savon noir, purin d'ortie",
                bonnesAssociations = "Basilic, carotte, tomate",
                mauvaisesAssociations = "Fenouil",
                conservation = "Conservation : Congélation : en lanières crues. Séchage : en poudre (paprika). Conserves : grillés à l'huile. Lactofermentation : en lanières salées.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Aubergine",
                categorie = "Fruit",
                difficulte = "Difficile",
                exposition = "Plein soleil",
                sol = "Riche, profond",
                arrosage = "Abondant au pied",
                temperature = "Très frileuse",
                semis = "Février à mars (sous abri)",
                plantation = "Mai",
                recolte = "Juillet à octobre",
                entretien = "Tuteurer, pailler",
                maladies = "Doryphore, mildiou",
                prevention = "Ramassage manuel, purin d'ortie",
                bonnesAssociations = "Haricot, basilic, thym",
                mauvaisesAssociations = "Pomme de terre",
                conservation = "Conservation : Congélation : en tranches grillées. Conserves : caviar d'aubergine stérilisé. Séchage : en tranches fines. Lactofermentation : en dés salés.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Concombre",
                categorie = "Fruit",
                difficulte = "Moyen",
                exposition = "Plein soleil",
                sol = "Riche, bien drainé",
                arrosage = "Très abondant",
                temperature = "Frileux",
                semis = "Mars à avril (sous abri)",
                plantation = "Mai",
                recolte = "Juillet à septembre",
                entretien = "Tuteurer, pailler",
                maladies = "Oïdium, mildiou",
                prevention = "Purin de prêle, éviter de mouiller les feuilles",
                bonnesAssociations = "Maïs, haricot, salade",
                mauvaisesAssociations = "Tomate, pomme de terre",
                conservation = "Conservation : Lactofermentation : en rondelles salées (pickles). Conserves : au vinaigre avec aromates. Congélation : en tranches pour smoothies. Réfrigérateur : 1 semaine.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Potiron",
                categorie = "Cucurbitacée",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Très riche en compost",
                arrosage = "Très abondant",
                temperature = "Frileux",
                semis = "Avril (sous abri)",
                plantation = "Mai",
                recolte = "Septembre à novembre",
                entretien = "Pailler, limiter les fruits par plant",
                maladies = "Oïdium, pourriture",
                prevention = "Purin de prêle, éviter de mouiller les feuilles",
                bonnesAssociations = "Maïs, haricot",
                mauvaisesAssociations = "Pomme de terre",
                conservation = "Conservation : Entier au sec et frais (3-6 mois). Congélation : en cubes blanchis. Conserves : purée stérilisée. Séchage : en lamelles déshydratées.",
                estVivace = false,
                estFleur = false
            ),

            // ===== LÉGUMES FEUILLES =====
            LegumeEntity(
                nom = "Salade",
                categorie = "Feuille",
                difficulte = "Facile",
                exposition = "Mi-ombre à soleil",
                sol = "Frais, riche en humus",
                arrosage = "Régulier, garder le sol frais",
                temperature = "Rustique, préfère la fraîcheur",
                semis = "Mars à septembre",
                plantation = "Repiquage ou semis direct",
                recolte = "4 à 8 semaines après semis",
                entretien = "Pailler pour garder l'humidité, éclaircir",
                maladies = "Limaces, botrytis",
                prevention = "Cendre autour des plants, purin de prêle",
                bonnesAssociations = "Carotte, radis, fraisier, concombre",
                mauvaisesAssociations = "Céleri, persil",
                conservation = "Conservation : Au réfrigérateur 1 semaine dans un linge humide. Lactofermentation : feuilles entières salées. Conserves : pesto de salade. Congélation : déconseillée.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Épinard",
                categorie = "Feuille",
                difficulte = "Facile",
                exposition = "Mi-ombre",
                sol = "Frais, riche en humus",
                arrosage = "Régulier, sol toujours frais",
                temperature = "Rustique",
                semis = "Mars à mai, août à septembre",
                plantation = "Semis direct",
                recolte = "6 à 8 semaines après semis",
                entretien = "Éclaircir, pailler",
                maladies = "Mildiou, pucerons",
                prevention = "Purin d'ortie, savon noir",
                bonnesAssociations = "Fraisier, pois, chou",
                mauvaisesAssociations = "Betterave",
                conservation = "Conservation : Congélation : blanchir 2 min puis congeler en portions. Conserves : purée stérilisée. Séchage : en poudre pour smoothies. Réfrigérateur : 3-5 jours.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Chou frisé (Kale)",
                categorie = "Feuille",
                difficulte = "Facile",
                exposition = "Soleil à mi-ombre",
                sol = "Riche, profond",
                arrosage = "Régulier",
                temperature = "Très rustique",
                semis = "Mars à juin",
                plantation = "Avril à juillet",
                recolte = "Septembre à mars",
                entretien = "Pailler, arroser",
                maladies = "Piéride du chou",
                prevention = "Voile anti-insectes",
                bonnesAssociations = "Oignon, pomme de terre, haricot",
                mauvaisesAssociations = "Fraise, tomate",
                conservation = "Conservation : Congélation : feuilles blanchies 2 min. Séchage : chips de kale au déshydrateur. Lactofermentation : feuilles salées. Réfrigérateur : 1 semaine.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Cardon",
                categorie = "Feuille ancienne",
                difficulte = "Moyen",
                exposition = "Plein soleil",
                sol = "Profond, riche, frais",
                arrosage = "Abondant en été",
                temperature = "Rustique",
                semis = "Avril à mai",
                plantation = "Mai à juin",
                recolte = "Octobre à décembre",
                entretien = "Butter, blanchir les côtes",
                maladies = "Pucerons",
                prevention = "Savon noir, purin d'ortie",
                bonnesAssociations = "Chou, haricot",
                mauvaisesAssociations = "Pomme de terre",
                conservation = "Conservation : En cave dans du sable (2-3 mois). Congélation : côtes blanchies 5 min. Conserves : côtes au naturel stérilisées.",
                estVivace = false,
                estFleur = false
            ),

            // ===== LÉGUMINEUSES =====
            LegumeEntity(
                nom = "Haricot vert",
                categorie = "Légumineuse",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Léger, bien drainé",
                arrosage = "Régulier, surtout à la floraison",
                temperature = "Craint le gel",
                semis = "Avril à juillet",
                plantation = "Semis direct",
                recolte = "2 à 3 mois après semis",
                entretien = "Butter les plants, pailler",
                maladies = "Anthracnose, rouille",
                prevention = "Rotation des cultures, purin de prêle",
                bonnesAssociations = "Maïs, courge, carotte",
                mauvaisesAssociations = "Ail, oignon, fenouil",
                conservation = "Conservation : Congélation : blanchir 3 min puis congeler. Conserves : en bocaux stérilisés. Lactofermentation : en bâtonnets salés. Séchage : haricots secs (variétés à écosser).",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Petit pois",
                categorie = "Légumineuse",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Léger, bien drainé",
                arrosage = "Régulier à la floraison",
                temperature = "Rustique",
                semis = "Février à mai",
                plantation = "Semis direct",
                recolte = "3 mois après semis",
                entretien = "Tuteurer, pailler",
                maladies = "Oïdium, anthracnose",
                prevention = "Purin de prêle, rotation des cultures",
                bonnesAssociations = "Carotte, radis, salade",
                mauvaisesAssociations = "Ail, oignon",
                conservation = "Conservation : Congélation : écossés puis congelés crus. Conserves : en bocaux stérilisés. Séchage : pois secs (laisser sécher sur pied).",
                estVivace = false,
                estFleur = false
            ),

            // ===== ALLIACÉS =====
            LegumeEntity(
                nom = "Oignon",
                categorie = "Alliacé",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Léger, bien drainé",
                arrosage = "Modéré, stopper avant récolte",
                temperature = "Rustique",
                semis = "Février à avril",
                plantation = "Mars à avril",
                recolte = "Juillet à septembre",
                entretien = "Biner, éviter l'humidité stagnante",
                maladies = "Mildiou, pourriture",
                prevention = "Rotation des cultures, purin de prêle",
                bonnesAssociations = "Carotte, betterave, salade",
                mauvaisesAssociations = "Haricot, pois",
                conservation = "Conservation : Séchage : tresser et suspendre au sec (6-8 mois). Conserves : confit d'oignon stérilisé. Lactofermentation : en rondelles salées. Congélation : émincés crus.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Poireau",
                categorie = "Alliacé",
                difficulte = "Moyen",
                exposition = "Soleil à mi-ombre",
                sol = "Riche, profond, frais",
                arrosage = "Régulier, surtout en été",
                temperature = "Très rustique",
                semis = "Février à avril",
                plantation = "Mai à juillet",
                recolte = "Octobre à mars",
                entretien = "Butter pour blanchir, pailler",
                maladies = "Rouille, teigne",
                prevention = "Purin de prêle, rotation des cultures",
                bonnesAssociations = "Carotte, céleri, fraisier",
                mauvaisesAssociations = "Haricot, pois",
                conservation = "Conservation : En terre tout l'hiver. Congélation : en rondelles blanchies 2 min. Séchage : en lamelles déshydratées. Réfrigérateur : 2 semaines.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Ail",
                categorie = "Alliacé",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Léger, bien drainé",
                arrosage = "Modéré",
                temperature = "Rustique",
                semis = "Octobre à novembre ou février à mars",
                plantation = "Octobre à novembre",
                recolte = "Juin à juillet",
                entretien = "Biner, éviter l'excès d'eau",
                maladies = "Rouille, pourriture",
                prevention = "Rotation des cultures, purin de prêle",
                bonnesAssociations = "Carotte, betterave, fraisier",
                mauvaisesAssociations = "Haricot, pois",
                conservation = "Conservation : Séchage : tresser et suspendre au sec (6-8 mois). Conserves : ail confit à l'huile. Lactofermentation : gousses entières salées. Congélation : gousses émincées.",
                estVivace = false,
                estFleur = false
            ),

            // ===== CHOUX =====
            LegumeEntity(
                nom = "Brocoli",
                categorie = "Chou",
                difficulte = "Moyen",
                exposition = "Plein soleil",
                sol = "Riche, profond, frais",
                arrosage = "Abondant et régulier",
                temperature = "Rustique",
                semis = "Mars à juin",
                plantation = "Avril à juillet",
                recolte = "3 à 4 mois après plantation",
                entretien = "Pailler, arroser régulièrement",
                maladies = "Piéride du chou, hernie",
                prevention = "Voile anti-insectes, rotation des cultures",
                bonnesAssociations = "Pomme de terre, oignon, aneth",
                mauvaisesAssociations = "Fraise, tomate",
                conservation = "Conservation : Congélation : fleurettes blanchies 3 min. Lactofermentation : fleurettes salées. Conserves : au naturel stérilisé. Réfrigérateur : 1 semaine.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Chou-fleur",
                categorie = "Chou",
                difficulte = "Moyen",
                exposition = "Plein soleil",
                sol = "Riche, profond, frais",
                arrosage = "Abondant et régulier",
                temperature = "Rustique",
                semis = "Mars à juin",
                plantation = "Avril à juillet",
                recolte = "3 à 4 mois après plantation",
                entretien = "Pailler, arroser régulièrement",
                maladies = "Piéride du chou, hernie",
                prevention = "Voile anti-insectes, rotation des cultures",
                bonnesAssociations = "Haricot, céleri, thym",
                mauvaisesAssociations = "Fraise, tomate",
                conservation = "Conservation : Congélation : fleurettes blanchies 3 min. Lactofermentation : fleurettes salées. Conserves : au vinaigre (pickles). Réfrigérateur : 1 semaine.",
                estVivace = false,
                estFleur = false
            ),

            // ===== HERBES AROMATIQUES =====
            LegumeEntity(
                nom = "Basilic",
                categorie = "Aromatique",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Riche, frais, bien drainé",
                arrosage = "Régulier, au pied",
                temperature = "Très frileux",
                semis = "Mars à mai (sous abri)",
                plantation = "Mai",
                recolte = "Juin à octobre",
                entretien = "Pincer les fleurs, récolter régulièrement",
                maladies = "Fonte des semis, mildiou",
                prevention = "Éviter l'excès d'eau, bonne aération",
                bonnesAssociations = "Tomate, poivron, courgette",
                mauvaisesAssociations = "Rue",
                conservation = "Conservation : Séchage : suspendre à l'ombre (1-2 semaines). Congélation : feuilles entières ou pesto. Conserves : pesto stérilisé. Réfrigérateur : 1 semaine dans l'eau.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Persil",
                categorie = "Aromatique",
                difficulte = "Facile",
                exposition = "Mi-ombre à soleil",
                sol = "Frais, riche, bien drainé",
                arrosage = "Régulier",
                temperature = "Rustique",
                semis = "Mars à août",
                plantation = "Semis direct",
                recolte = "Toute l'année",
                entretien = "Couper les feuilles régulièrement",
                maladies = "Mildiou, pucerons",
                prevention = "Purin d'ortie, savon noir",
                bonnesAssociations = "Tomate, carotte, oignon",
                mauvaisesAssociations = "Salade",
                conservation = "Conservation : Séchage : suspendre à l'ombre (1-2 semaines). Congélation : feuilles ciselées. Conserves : huile parfumée. Réfrigérateur : 1-2 semaines.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Menthe",
                categorie = "Aromatique",
                difficulte = "Très facile",
                exposition = "Mi-ombre",
                sol = "Frais, riche",
                arrosage = "Abondant",
                temperature = "Très rustique",
                semis = "Mars à mai (plantation)",
                plantation = "Mars à mai",
                recolte = "Avril à octobre",
                entretien = "Limiter l'expansion, tailler",
                maladies = "Rouille",
                prevention = "Purin de prêle, aération",
                bonnesAssociations = "Chou, tomate, courgette",
                mauvaisesAssociations = "Aucune",
                conservation = "Conservation : Séchage : suspendre à l'ombre (1-2 semaines). Congélation : feuilles entières. Conserves : sirop de menthe. Réfrigérateur : 1 semaine dans l'eau.",
                estVivace = true,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Thym",
                categorie = "Aromatique",
                difficulte = "Très facile",
                exposition = "Plein soleil",
                sol = "Sec, pauvre, bien drainé",
                arrosage = "Faible, résiste à la sécheresse",
                temperature = "Rustique",
                semis = "Mars à mai",
                plantation = "Mars à mai",
                recolte = "Toute l'année",
                entretien = "Tailler après floraison",
                maladies = "Aucune majeure",
                prevention = "Bonne aération",
                bonnesAssociations = "Chou, fraisier, aubergine",
                mauvaisesAssociations = "Aucune",
                conservation = "Conservation : Séchage : suspendre à l'ombre (1-2 semaines). Conserves : huile parfumée au thym. Congélation : branches entières. Réfrigérateur : 2 semaines.",
                estVivace = true,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Romarin",
                categorie = "Aromatique",
                difficulte = "Très facile",
                exposition = "Plein soleil",
                sol = "Sec, calcaire, bien drainé",
                arrosage = "Faible",
                temperature = "Rustique",
                semis = "Mars à mai (plantation)",
                plantation = "Mars à mai",
                recolte = "Toute l'année",
                entretien = "Tailler après floraison",
                maladies = "Aucune majeure",
                prevention = "Bonne aération",
                bonnesAssociations = "Haricot, chou, carotte",
                mauvaisesAssociations = "Aucune",
                conservation = "Conservation : Séchage : suspendre à l'ombre (1-2 semaines). Conserves : huile parfumée au romarin. Congélation : branches entières. Réfrigérateur : 2 semaines.",
                estVivace = true,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Ciboulette",
                categorie = "Aromatique",
                difficulte = "Très facile",
                exposition = "Soleil à mi-ombre",
                sol = "Frais, riche",
                arrosage = "Régulier",
                temperature = "Rustique",
                semis = "Mars à mai",
                plantation = "Mars à mai",
                recolte = "Avril à octobre",
                entretien = "Couper régulièrement",
                maladies = "Rouille",
                prevention = "Purin de prêle",
                bonnesAssociations = "Carotte, tomate, pomme de terre",
                mauvaisesAssociations = "Haricot, pois",
                conservation = "Conservation : Congélation : ciseaux dans un sac. Séchage : à plat à l'ombre. Conserves : vinaigre parfumé. Réfrigérateur : 1-2 semaines.",
                estVivace = true,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Coriandre",
                categorie = "Aromatique",
                difficulte = "Facile",
                exposition = "Soleil à mi-ombre",
                sol = "Léger, frais, bien drainé",
                arrosage = "Régulier",
                temperature = "Rustique",
                semis = "Mars à septembre",
                plantation = "Semis direct",
                recolte = "6 à 8 semaines après semis",
                entretien = "Éclaircir, récolter les feuilles",
                maladies = "Fonte des semis",
                prevention = "Bonne aération",
                bonnesAssociations = "Carotte, chou, concombre",
                mauvaisesAssociations = "Fenouil",
                conservation = "Conservation : Congélation : feuilles ciselées. Séchage : graines (coriandre en grains). Conserves : pesto de coriandre. Réfrigérateur : 1 semaine.",
                estVivace = false,
                estFleur = false
            ),
            LegumeEntity(
                nom = "Aneth",
                categorie = "Aromatique",
                difficulte = "Facile",
                exposition = "Plein soleil",
                sol = "Léger, bien drainé",
                arrosage = "Modéré",
                temperature = "Rustique",
                semis = "Avril à juillet",
                plantation = "Semis direct",
                recolte = "Juin à septembre",
                entretien = "Éclaircir, tuteurer si nécessaire",
                maladies = "Fonte des semis",
                prevention = "Bonne aération",
                bonnesAssociations = "Chou, concombre, oignon",
                mauvaisesAssociations = "Carotte, tomate",
                conservation = "Conservation : Séchage : suspendre à l'ombre (1-2 semaines). Congélation : feuilles ciselées. Conserves : vinaigre parfumé à l'aneth. Réfrigérateur : 1 semaine.",
                estVivace = false,
                estFleur = false
            ),

            // ===== FLEURS =====
            LegumeEntity(
                nom = "Lavande",
                categorie = "Fleur vivace",
                difficulte = "Très facile",
                exposition = "Plein soleil",
                sol = "Sec, calcaire, bien drainé",
                arrosage = "Faible, résiste à la sécheresse",
                temperature = "Rustique",
                semis = "Mars à mai (plantation)",
                plantation = "Mars à mai",
                recolte = "Juin à août (fleurs)",
                entretien = "Tailler après floraison",
                maladies = "Aucune majeure",
                prevention = "Bonne aération",
                bonnesAssociations = "Tomate, chou, rosier",
                mauvaisesAssociations = "Aucune",
                conservation = "Conservation : Séchage : suspendre les bouquets à l'ombre. Conserves : huile parfumée à la lavande. Sachets parfumés.",
                estVivace = true,
                estFleur = true
            ),
            LegumeEntity(
                nom = "Capucine",
                categorie = "Fleur annuelle",
                difficulte = "Très facile",
                exposition = "Soleil à mi-ombre",
                sol = "Léger, même pauvre",
                arrosage = "Modéré",
                temperature = "Craint le gel",
                semis = "Avril à mai",
                plantation = "Semis direct",
                recolte = "Juin à octobre",
                entretien = "Aucun entretien particulier",
                maladies = "Pucerons (plante piège)",
                prevention = "Utiliser comme plante sacrificielle",
                bonnesAssociations = "Tomate, chou, courgette",
                mauvaisesAssociations = "Aucune",
                conservation = "Conservation : Fleurs au réfrigérateur 2-3 jours. Graines lactofermentées (câpres de capucine). Vinaigre parfumé.",
                estVivace = false,
                estFleur = true
            ),
            LegumeEntity(
                nom = "Souci",
                categorie = "Fleur annuelle",
                difficulte = "Très facile",
                exposition = "Plein soleil",
                sol = "Tout sol drainé",
                arrosage = "Modéré",
                temperature = "Rustique",
                semis = "Mars à mai",
                plantation = "Semis direct",
                recolte = "Mai à octobre",
                entretien = "Supprimer les fleurs fanées",
                maladies = "Oïdium",
                prevention = "Bonne aération",
                bonnesAssociations = "Tomate, chou, carotte",
                mauvaisesAssociations = "Aucune",
                conservation = "Conservation : Fleurs séchées pour tisanes. Pétales au réfrigérateur 3 jours. Huile de souci.",
                estVivace = false,
                estFleur = true
            ),
            LegumeEntity(
                nom = "Bourrache",
                categorie = "Fleur annuelle",
                difficulte = "Très facile",
                exposition = "Plein soleil",
                sol = "Tout sol",
                arrosage = "Modéré",
                temperature = "Rustique",
                semis = "Mars à mai",
                plantation = "Semis direct",
                recolte = "Mai à septembre",
                entretien = "Se ressème spontanément",
                maladies = "Aucune majeure",
                prevention = "Bonne aération",
                bonnesAssociations = "Fraisier, tomate, courgette",
                mauvaisesAssociations = "Aucune",
                conservation = "Conservation : Fleurs au réfrigérateur 2 jours. Congélation dans glaçons. Séchage pour tisanes.",
                estVivace = false,
                estFleur = true
            ),
            LegumeEntity(
                nom = "Phacélie",
                categorie = "Fleur annuelle",
                difficulte = "Très facile",
                exposition = "Plein soleil",
                sol = "Tout sol",
                arrosage = "Faible",
                temperature = "Rustique",
                semis = "Mars à septembre",
                plantation = "Semis direct",
                recolte = "6-8 semaines après semis",
                entretien = "Faucher avant montée en graines (engrais vert)",
                maladies = "Aucune majeure",
                prevention = "Bonne aération",
                bonnesAssociations = "Tous les légumes",
                mauvaisesAssociations = "Aucune",
                conservation = "Conservation : Engrais vert à enfouir. Fleurs pour pollinisateurs. Miel de phacélie.",
                estVivace = false,
                estFleur = true
            ),
            LegumeEntity(
                nom = "Cosmos",
                categorie = "Fleur annuelle",
                difficulte = "Très facile",
                exposition = "Plein soleil",
                sol = "Tout sol drainé",
                arrosage = "Faible",
                temperature = "Craint le gel",
                semis = "Avril à mai",
                plantation = "Semis direct",
                recolte = "Juin à octobre",
                entretien = "Tuteurer si nécessaire",
                maladies = "Aucune majeure",
                prevention = "Bonne aération",
                bonnesAssociations = "Tous les légumes",
                mauvaisesAssociations = "Aucune",
                conservation = "Conservation : Fleurs séchées décoratives. Bouquets frais 1 semaine.",
                estVivace = false,
                estFleur = true
            ),
            LegumeEntity(
                nom = "Œillet d'Inde",
                categorie = "Fleur annuelle",
                difficulte = "Très facile",
                exposition = "Plein soleil",
                sol = "Tout sol drainé",
                arrosage = "Modéré",
                temperature = "Craint le gel",
                semis = "Mars à mai",
                plantation = "Semis direct ou repiquage",
                recolte = "Juin à octobre",
                entretien = "Supprimer les fleurs fanées",
                maladies = "Aucune majeure",
                prevention = "Bonne aération",
                bonnesAssociations = "Tomate, pomme de terre, chou",
                mauvaisesAssociations = "Aucune",
                conservation = "Conservation : Fleurs séchées. Bouquets frais 1 semaine. Répulsif naturel contre nématodes.",
                estVivace = false,
                estFleur = true
            )
        )
    }
}
